services:
  mage:
    image: mageai/mageai
    # ports:
    #   - "6789:6789"
    volumes: 
     - ./workspace:/home/src
    labels:
      - "traefik.http.routers.mage.rule=Host(`mage.localhost`)"
      - "traefik.http.services.mage.loadbalancer.server.port=6789"
    command: sh -c "pip3 install -r /home/src/homework_03/requirements.txt && /app/run_app.sh mage start homework_03"
  mlflow:
    build:
      context: .
      dockerfile: mlflow.dockerfile
    # ports:
    #   - "5000:5000"
    volumes:
      - .mlflow_data:/home/mlflow_data/
    labels:
      - "traefik.http.routers.mlflow.rule=Host(`mlflow.localhost`)"
      - "traefik.http.services.mlflow.loadbalancer.server.port=5000"
  reverse-proxy:
    image: traefik:v3.1
    command: --api.insecure=true --providers.docker --entrypoints.web.address=:80
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro